version: 2

sources:
  - name: taxi_trips_tdc
    database: bigquery-public-data
    schema: chicago_taxi_trips
    tables:
      - name: taxi_trips     
        description: "Raw taxi trips data"
      
  - name: us_holiday_tdc
    database: macro-crane-464804-d0
    schema: dbt_times_dot_com
    tables:
      - name: us_holiday     
        description: "US holidays from Kaggle dataset "

  - name: staging_taxi_trips_tdc
    database: macro-crane-464804-d0
    schema: dbt_times_dot_com
    tables:
      - name: stg_taxi_trips  
        description: "Staging Dataset "